version: "3.8"

services:
  postgres:
    image: postgres:16.1-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${USERPASS}
    ports:
      - "5432:5432"
    volumes:
      - go-webapp-demo-db:/var/lib/postgresql/data

volumes:
  go-webapp-demo-db: